# Generated by Django 5.2.12 on 2026-03-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.IntegerField()),
                ("shipping_method", models.CharField(default="STANDARD", max_length=50)),
                ("address", models.CharField(default="", max_length=255)),
                ("status", models.CharField(default="PENDING", max_length=50)),
            ],
        ),
    ]
