# Generated by Django 5.2.12 on 2026-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_id", models.IntegerField()),
                ("book_id", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, default="")),
            ],
        ),
    ]
