# Generated by Django 5.2.12 on 2026-03-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.IntegerField()),
                ("payment_method", models.CharField(default="COD", max_length=50)),
                ("status", models.CharField(default="PENDING", max_length=50)),
            ],
        ),
    ]
